version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash -c "uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload && alembic upgrade head"
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"